#Importing pandas

In [10]:
import numpy as np
import pandas as pd

#Series from list

In [2]:
#string

country=['Indai','pakistan','nepal','dubai','sri lanka']
pd.Series(country)

0        Indai
1     pakistan
2        nepal
3        dubai
4    sri lanka
dtype: object

In [3]:
#integer

runs=[53,23,55,93,24]
pd.Series(runs)

0    53
1    23
2    55
3    93
4    24
dtype: int64

In [5]:
#custom series
subject=['english','science','sst','hindi','maths']
marks=[93,34,83,20,92]
pd.Series(marks,index=subject)

english    93
science    34
sst        83
hindi      20
maths      92
dtype: int64

In [6]:
#setting name
pd.Series(marks,index=subject,name='santosh ke marks')

english    93
science    34
sst        83
hindi      20
maths      92
Name: santoh ke marks, dtype: int64

In [17]:
#using Dictionaries

marks={
    "english":78,
    "hindi":44,
    "maths":47
}

marks_series=pd.Series(marks ,name="santosh ke marks")
marks_series

english    78
hindi      44
maths      47
Name: santosh ke marks, dtype: int64

# Series Attributes

In [11]:
#size
marks_series.size

3

In [12]:
#dtype
marks_series.dtype

dtype('int64')

In [13]:
#name
marks_series.name

'santosh ke marks'

In [18]:
#is_unique
marks_series.is_unique

True

In [19]:
#index

marks_series.index

Index(['english', 'hindi', 'maths'], dtype='object')

In [20]:
#values
marks_series.values

array([78, 44, 47])

#Series using read_csv

In [22]:
# with 1 col

In [30]:
sub=pd.read_csv('/subs.csv')
sub

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
#with 2 col