In [1]:
import numpy as np 
import pandas as pd

### Pivot Tables

In [2]:

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [6]:
df=pd.DataFrame(data)
df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+ df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    963     70   John  January      Q1
1  2023-01-02       B   West    398     94   Mary  January      Q1
2  2023-01-03       C  North    944     81    Bob  January      Q1
3  2023-01-04       D  South    103     69  Alice  January      Q1
4  2023-01-05       A   East    443     82   John  January      Q1
5  2023-01-06       B   West    713     93   Mary  January      Q1
6  2023-01-07       C  North    998     42    Bob  January      Q1
7  2023-01-08       D  South    984     74  Alice  January      Q1
8  2023-01-09       A   East    153     13   John  January      Q1
9  2023-01-10       B   West    966     87   Mary  January      Q1
10 2023-01-11       C  North    883     96    Bob  January      Q1
11 2023-01-12       D  South    290     12  Alice  January      Q1
12 2023-01-13       A   East    577     57   John  January      Q1
13 2023-01-14       B   West    499     39   Mary  January      Q1
14 2023-01-15       C  North    832     82    Bob  January      Q1
15 2023-01-16       D  South    200     62  Alice  January      Q1
16 2023-01-17       A   East    534     19   John  January      Q1
17 2023-01-18       B   West    474     40   Mary  January      Q1
18 2023-01-19       C  North    211     64    Bob  January      Q1
19 2023-01-20       D  South    913     56  Alice  January      Q1

In [8]:
pd.pivot_table(df,values="Sales" ,index="Region", columns="Product")

Product      A      B      C      D
Region
East     534.0    NaN    NaN    NaN
North      NaN    NaN  773.6    NaN
South      NaN    NaN    NaN  498.0
West       NaN  610.0    NaN    NaN

In [10]:
pivot2=pd.pivot_table(df,values=['Sales','Units'] ,index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     534.0    NaN    NaN    NaN  48.2   NaN   NaN   NaN
North      NaN    NaN  773.6    NaN   NaN   NaN  73.0   NaN
South      NaN    NaN    NaN  498.0   NaN   NaN   NaN  54.6
West       NaN  610.0    NaN    NaN   NaN  70.6   NaN   NaN

## Cross Tab

In [11]:
#this is used for counting purpose

pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0